eig_rel – foreig
eig_rel Subroutine
Seyed Ali Ghasemi
19 statements
Source File
private pure subroutine eig_rel(matrix, eig_vecr, eig_val, eig_vecl, method)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:,:) :: matrix
real(kind=rk), intent(out), dimension(:,:), allocatable :: eig_vecr
real(kind=rk), intent(out), dimension(:), allocatable :: eig_val
real(kind=rk), intent(out), optional, dimension(:,:), allocatable :: eig_vecl
character(len=*), intent(in), optional :: method
Calls
Called by
Contents
Source Code
eig_rel
Source Code
   pure subroutine eig_rel(matrix, eig_vecr, eig_val, eig_vecl, method)
      real(rk), dimension(:,:),              intent(in)            :: matrix
      character(*),                          intent(in), optional  :: method
      real(rk), dimension(:,:), allocatable, intent(out)           :: eig_vecr
      real(rk), dimension(:,:), allocatable, intent(out), optional :: eig_vecl
      real(rk), dimension(:),   allocatable, intent(out)           :: eig_val
      if (.not. present(method)) then
         call dgeev_rel(matrix, eig_vecr, eig_val)
      else
         select case (method)
          case ('syev')
            call dsyev_rel(matrix, eig_vecr, eig_val)
          case ('geev')
            call dgeev_rel(matrix, eig_vecr, eig_val, eig_vecl)
          case ('ggev')
            call dggev_rel(matrix, eig_vecr, eig_val, eig_vecl)
         end select
      end if
   end subroutine eig_rel
Call graph
eig_rel calls dgeev_rel, dggev_rel, dsyev_rel
eig calls eig_rel
benchmark calls eig
test1 calls eig