eig – foreig
eig Interface
3 statements
Source File
public interface eig
Calls
Called by
Contents
Module Procedures
eig_rel
Module Procedures
private pure subroutine eig_rel(matrix, eig_vecr, eig_val, eig_vecl, method)
Author
Seyed Ali Ghasemi
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:,:) :: matrix
real(kind=rk), intent(out), dimension(:,:), allocatable :: eig_vecr
real(kind=rk), intent(out), dimension(:), allocatable :: eig_val
real(kind=rk), intent(out), optional, dimension(:,:), allocatable :: eig_vecl
character(len=*), intent(in), optional :: method
Call graph
eig calls eig_rel
eig_rel calls dgeev_rel, dggev_rel, dsyev_rel
benchmark calls eig
test1 calls eig