test1 – foreig
test1 Program
14 statements
Source File
Uses
foreig
kinds
Calls
Variables
Type Attributes Name Initial
real(kind=rk), dimension(:,:), allocatable :: A
real(kind=rk), dimension(:,:), allocatable :: eig_vec
real(kind=rk), dimension(:), allocatable :: eig_val
Source Code
program test1
   use kinds
   use foreig, only: eig
   implicit none
   real(rk), dimension(:,:), allocatable :: A
   real(rk), dimension(:,:), allocatable :: eig_vec
   real(rk), dimension(:),   allocatable :: eig_val
   allocate(A(5,5), eig_vec(5,5), eig_val(5))
   call random_number(A)
   call eig(A, eig_vec, eig_val)
   print*, eig_vec
   print*, eig_val
   deallocate(A, eig_vec, eig_val)
end program test1
Call graph
test1 calls eig
eig calls eig_rel
eig_rel calls dgeev_rel, dggev_rel, dsyev_rel